# Generated by Django 4.2.7 on 2025-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('conversation_history', models.JSONField(default=list)),
                ('current_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinToneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('uploaded_image', models.ImageField(upload_to='skin_analysis/')),
                ('skin_tone', models.CharField(choices=[('deep_warm', 'Deep Warm'), ('deep_cool', 'Deep Cool'), ('tan_warm', 'Tan Warm'), ('medium_warm', 'Medium Warm'), ('medium_cool', 'Medium Cool'), ('olive_cool', 'Olive Cool'), ('fair_warm', 'Fair Warm'), ('light_cool', 'Light Cool')], max_length=20)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool')], max_length=10)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=10)),
                ('rgb_values', models.JSONField()),
                ('hsv_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('liked', models.BooleanField()),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('session_id', 'product_id')},
            },
        ),
    ]
