# Generated by Django 4.2.7 on 2025-08-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tailoring', '0002_alter_tailoredresume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailoredresume',
            name='template_used',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('modern', 'Modern'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
