# Generated by Django 4.2.7 on 2025-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0002_alter_resumeanalysis_user_alter_resumeupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
