# Generated by Django 4.2.7 on 2025-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_prep', '0002_alter_interviewchat_user_alter_interviewsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='company_name',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='experience_level',
            field=models.CharField(default='mid', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_type',
            field=models.CharField(default='behavioral', max_length=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_title',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tips_generated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
