# Generated by Django 4.2.7 on 2025-08-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_prep', '0003_interviewsession_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtip',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
