# Generated by Django 4.2.7 on 2025-08-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_prep', '0004_interviewtip_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtip',
            name='session_id',
        ),
    ]
